<?php


return [
    'api' => [
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'audit',
            'handler' => 'progress',
            'permission' => 'api-erm-audit-progress',
            'role' => [
                'admin',
                'grc_admin', 
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'meta',
            'handler' => 'manager',
            'permission' => 'api-erm-meta-manager',
            'role' => [
                'admin',
                'grc_admin',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'compliance',
            'handler' => 'task',
            'permission' => 'api-erm-compliance-task',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'insurance',
            'handler' => 'task',
            'permission' => 'api-erm-insurance-task',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'insurance',
            'handler' => 'domain',
            'permission' => 'api-erm-insurance-domain',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'maturity',
            'handler' => 'task',
            'permission' => 'api-erm-maturity-task',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'maturity',
            'handler' => 'domain',
            'permission' => 'api-erm-maturity-domain',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'risk',
            'handler' => 'dashboard',
            'permission' => 'api-erm-risk-dashboard',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'compliance',
            'handler' => 'dashboard',
            'permission' => 'api-erm-compliance-dashboard',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'risk',
            'handler' => 'progress',
            'permission' => 'api-erm-risk-progress',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'risk',
            'handler' => 'list',
            'permission' => 'api-erm-risk-list',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],


        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'compliance',
            'handler' => 'progress',
            'permission' => 'api-erm-compliance-progress',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],

        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'role',
            'handler' => 'list',
            'permission' => 'api-erm-role-list',
            'role' => [
                'admin',
                'grc_admin',
            ],
        ],

        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'member',
            'handler' => 'list',
            'permission' => 'api-erm-member-list',
            'role' => [
                'admin',
                'grc_admin',
            ],
        ],
        [
            'title'       => 'ERM API member light list',
            'module'      => 'erm',
            'section'     => 'api',
            'package'     => 'member',
            'handler'     => 'light-list',
            'permission'  => 'api-erm-member-light-list',
            'permissions' => 'api-erm-member-light-list',
            'page'        => 'api-erm-member-light-list',
            'role'        => [
                'admin',
                'grc_admin',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'member',
            'handler' => 'add',
            'permission' => 'api-erm-member-add',
            'role' => [
                'admin',
                'grc_admin',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'member',
            'handler' => 'delete',
            'permission' => 'api-erm-member-delete',
            'role' => [
                'member',
                'admin',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'member',
            'handler' => 'edit',
            'permission' => 'api-erm-member-edit',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'rule',
            'handler' => 'list',
            'permission' => 'api-erm-rule-list',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'title'       => 'ERM API rule light list',
            'module'      => 'erm',
            'section'     => 'api',
            'package'     => 'rule',
            'handler'     => 'light-list',
            'permission'  => 'api-erm-rule-light-list',
            'permissions' => 'api-erm-rule-light-list',
            'page'        => 'api-erm-rule-light-list',
            'role'        => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'rule',
            'handler' => 'add',
            'permission' => 'api-erm-rule-add',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'rule',
            'handler' => 'edit',
            'permission' => 'api-erm-rule-edit',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'rule',
            'handler' => 'delete',
            'permission' => 'api-erm-rule-delete',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],


        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'task',
            'handler' => 'list',
            'permission' => 'api-erm-task-list',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'task',
            'handler' => 'add',
            'permission' => 'api-erm-task-add',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'task',
            'handler' => 'edit',
            'permission' => 'api-erm-task-edit',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'task',
            'handler' => 'delete',
            'permission' => 'api-erm-task-delete',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],

        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'warranty',
            'handler' => 'list',
            'permission' => 'api-erm-warranty-list',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
        [
            'module' => 'erm',
            'section' => 'api',
            'package' => 'domain',
            'handler' => 'tree',
            'permission' => 'api-erm-domain-tree',
            'role' => [
                'admin',
                'member',
                'grc_admin',
                'grc_member',
            ],
        ],
    ],

    'admin' => [
        [
            'title'       => 'Admin ERM rule light list',
            'module'      => 'erm',
            'section'     => 'admin',
            'package'     => 'rule',
            'handler'     => 'light-list',
            'permission'  => 'admin-erm-rule-light-list',
            'permissions' => 'admin-erm-rule-light-list',
            'page'        => 'admin-erm-rule-light-list',
            'role'        => [
                'admin',
                'grc_admin',
            ],
        ],
        [
            'title'       => 'Admin ERM member light list',
            'module'      => 'erm',
            'section'     => 'admin',
            'package'     => 'member',
            'handler'     => 'light-list',
            'permission'  => 'admin-erm-member-light-list',
            'permissions' => 'admin-erm-member-light-list',
            'page'        => 'admin-erm-member-light-list',
            'role'        => [
                'admin',
                'grc_admin',
            ],
        ],
    ],

];